### ISSUE TITLE
Old channel assignment in bundle causes unexpected errors on attempted upload

### ISSUE THREAD

**Issue by lazypower** [juju/charmstore#684]
During prior dev cycles, I pushed a bundle that referenced a development channel.

The channels have since changed to mirror the Snappy channel layout:
- Edge
- ReleaseCandidate
- Beta
- Stable

When I attempt to update the bundle in the store, it complains at me that i'm referencing a charm outside of this channel format:

```
charles@Tennoki ~/work/bundles/beats-core $ charm push . cs:~containers/bundle/beats-core
ERROR cannot post archive: cannot check for existing entities: cannot find entities matching cs:~containers/beats-core: charm or bundle URL has invalid form: "cs:~containers/development/trusty/filebeat"
```

Whats interesting is this is one of the only bundles that appears to be bitten by this bug, and i believe its due to that stale revision in the bundle tree. 

I'm only assuming here but i think this is during the computation of what the bundle consumes/relates to - and during that ingest sequence its complaining heavilly.

The bundle i'm attempting to push looks like the following:

``` yaml

series: trusty
services:
  kibana:
    charm: cs:trusty/kibana-15
    num_units: 1
    expose: true
    options:
      dashboards: beats
    annotations:
      gui-x: '987'
      gui-y: '900'
  elasticsearch:
    charm: cs:trusty/elasticsearch-19
    num_units: 1
    annotations:
      gui-x: '680'
      gui-y: '900'
  filebeat:
    charm: cs:filebeat-5
    annotations:
      gui-x: '352'
      gui-y: '654'
  topbeat:
    charm: cs:topbeat-5
    annotations:
      gui-x: '352'
      gui-y: '854'
relations:
- - kibana:rest
  - elasticsearch:client
- - filebeat:elasticsearch
  - elasticsearch:client
- - topbeat:elasticsearch
  - elasticsearch:client
```

All references to that stale revision have been cleaned up, so its got to be due to the stale bundle in the revision history causing the problem.

```
 $ charm show cs:~containers/bundle/beats-core revision-info
revision-info:
  Revisions:
  - cs:~containers/bundle/beats-core-9
  - cs:~containers/bundle/beats-core-8
  - cs:~containers/bundle/beats-core-7
  - cs:~containers/bundle/beats-core-6
  - cs:~containers/bundle/beats-core-5
  - cs:~containers/bundle/beats-core-4
  - cs:~containers/bundle/beats-core-3
  - cs:~containers/bundle/beats-core-2
  - cs:~containers/bundle/beats-core-1
  - cs:~containers/bundle/beats-core-0
```

Is there a way i can remove those stale bundles, so we can unblock the release progression of teh beats core bundle? or would i need to wholesale remove permissions and start with a fresh push target?

eg:

```
charm push . cs:~containers/bundle/elastic-stack-beats
```
